## Alternative 1: Single target execution.
##
##
## Alternative 2: Multiple target tandem execution.
##      bin/targets | xargs mk
##
## Alternative 3: Multiple target parallel execution. NOTE: requires HTCondor.
##      condor submit
##
## AUTHOR:
##      Fernando Perez (fperez@inmegen.edu.mx) - 2018


< ../config.mk

#Execute eigensoft for each subset and generate the Fst distance matrix in phylip format
results/%.dist.phylip:	results/%.par
	set -x
	mkdir -p `dirname ${target}`
	echo -e "data/"${stem}".dist.phylip\nO\n$OUT\ny\n" \
		| neighbor \
	&& mv outree ${target} \
	&& mv outfile "results/"${stem}"_phylip"
